### PR TITLE
Extract out xrpackage.org frontend web

### PR DESCRIPTION
**Pull request by shu8**
This adds the files removed in https://github.com/webaverse/xrpackage/pull/49 to this repo.

As part of https://github.com/webaverse/xrpackage/issues/36.

### CODE REVIEW

**Comment by shu8** [comment]
I think this should be ready for review now.

If you're testing locally, you'll need to (temporarily) revert https://github.com/webaverse/xrpackage-site/pull/2/commits/43027ee254a3e77e0373aac8007b3af1cd6cabd1 (where I updated URLs from xrpackage.org to static.xrpackage.org)

https://github.com/webaverse/xrpackage/pull/49 would need to be deployed first, with that repo now serving `static.xrpackage.org`.

We should also probably setup 301 redirects for the JS files that were on xrpackage.org previously (i.e. this new repo) so that it doesn't break any existing scripts elsewhere. e.g. `xrpackage.org/xrpackage.js` => `static.xrpackage.org/xrpackage.js`.

**Comment by shu8** [comment]
I'd also like to lint this entire repo once we're happy with the code, but I think it's probably best to do that in a separate PR so it's easier to review this one.

It might be worth deciding on an ESLint config that we're happy with so that we can use it throughout Webaverse projects, as currently the code style seems to be quite mixed.

https://github.com/webaverse/xrpackage/issues/32 says we use roughly `semistandard` code style.

The main additions to that I can see we use are trailing commas, so would an ESLint config like:

```
{
    "extends": "semistandard",
    "rules": {
        "comma-dangle": ["error", "always"]
    },
    "env": {
        "browser": true // or `"node": true `, for different projects
    }
}
```

work for us?

**Comment by avaer** [comment]
> I'd also like to lint this entire repo once we're happy with the code, but I think it's probably best to do that in a separate PR so it's easier to review this one.
> It might be worth deciding on an ESLint config that we're happy with so that we can use it throughout Webaverse projects, as currently the code style seems to be quite mixed.

Yes I like that idea.

I think the main difference in the code style between the lint files and what we had in the last pass was
- dangling commas
- `{tightBrackets}` instead of `{ spacedBrackets }`

I'm not sure the eslint setting for the latter.

**Comment by avaer** [comment]
For the redirect rules I think we'll need exactly three things mapping to `static.xrpackage.org`:

- `xrpackage.js`
- `sw.js`
- `xrpackage/*`

I'll need to double check that these are the only things in the API surface but that was the intent.

**Comment by shu8** [comment]
Looks like it's [`object-curly-spacing`](https://eslint.org/docs/rules/object-curly-spacing#never)!

So I think we've ended with:

```
{
    "extends": "semistandard",
    "rules": {
        "comma-dangle": ["error", "always"],
        "object-curly-spacing": ["error", "never"]
    },
    "env": {
        "browser": true // or `"node": true `, for different projects
    }
}
```

**Comment by shu8** [comment]
Potentially `selector.js` might need mapping, I'm not sure if all the sites that use it use it locally or fetch it from the remote

**Comment by avaer** [comment]
I think `selector.js` is supposed to be part of the frontend, not the core API. It is what controls the selector in the header and really has nothing to do with the engine core.

**Comment by avaer** [comment]
Are you able to confirm whether the source in this PR is up to date with https://github.com/webaverse/xrpackage/commit/8138a6d292c3ec22abf57f1423b524b265a46c62 ? It looks like the commits started after that one so that would make sense but I'd like to make sure we aren't missing anything.

**Comment by shu8** [comment]
@avaer I just went through the commits from the last few days on the xrpackage repo - I can't find anything relating to the web files that I've missed!

Only https://github.com/webaverse/xrpackage/commit/957be4c8e8f9a960270acdc991cd0dc99a6b826c seems relevant and I've incorporated that in this PR

**Comment by shu8** [comment]
Awesome! I noticed a few things at https://webaverse.github.io/xrpackage-site/src/

- Looks like the files need to be in the root directory of the repo? unless there's a way to specify the `src` folder as the root of the site?
- We might need to temporarily revert https://github.com/webaverse/xrpackage-site/commit/43027ee254a3e77e0373aac8007b3af1cd6cabd1 to be able to test it properly (unless we merge https://github.com/webaverse/xrpackage/pull/49 first)

**Pull request merged**
